<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="p-5 mb-4 bg-light rounded-3">
    <h1 class="display-4">Welcome to<br>Hamid Teimouri</h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/laminas/laminas-mvc-skeleton" target="_blank">Laminas MVC Skeleton</a>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on Laminas MVC.
    </p>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="https://github.com/laminas" target="_blank">
        Check Laminas on GitHub &raquo;
    </a>
</div>
